// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWVtAvBIQ7l9lmj6Lxk8PpEcq7A8XS1k8',
    appId: '1:850465034079:web:74f12d5ea4b71e81cb70ea',
    messagingSenderId: '850465034079',
    projectId: 'flutter-74bac',
    authDomain: 'flutter-74bac.firebaseapp.com',
    storageBucket: 'flutter-74bac.appspot.com',
    measurementId: 'G-8MMPE00T2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHOI8OOEgaw3ZFWIk3Xg6lxhUtli_5X5U',
    appId: '1:850465034079:android:60031e6aadb63ce0cb70ea',
    messagingSenderId: '850465034079',
    projectId: 'flutter-74bac',
    storageBucket: 'flutter-74bac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqatDpGQU18EZhXQsoLOw9MrmzYSGJTEU',
    appId: '1:850465034079:ios:d4da7aa4c983d39dcb70ea',
    messagingSenderId: '850465034079',
    projectId: 'flutter-74bac',
    storageBucket: 'flutter-74bac.appspot.com',
    iosClientId: '850465034079-vabjfn8pnuoikig0tv30p70agkrqr5i4.apps.googleusercontent.com',
    iosBundleId: 'com.michelle.appBbdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqatDpGQU18EZhXQsoLOw9MrmzYSGJTEU',
    appId: '1:850465034079:ios:d4da7aa4c983d39dcb70ea',
    messagingSenderId: '850465034079',
    projectId: 'flutter-74bac',
    storageBucket: 'flutter-74bac.appspot.com',
    iosClientId: '850465034079-vabjfn8pnuoikig0tv30p70agkrqr5i4.apps.googleusercontent.com',
    iosBundleId: 'com.michelle.appBbdd',
  );
}
